"""add client contact fields

Revision ID: 9f5f7e048031
Revises: 4af016d81db5
Create Date: 2025-10-07 18:10:22.773813

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5f7e048031'
down_revision: Union[str, Sequence[str], None] = '4af016d81db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('customer_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'customer_phone')
    op.drop_column('shipment', 'customer_email')
    # ### end Alembic commands ###
