"""Added tags to shipment

Revision ID: 7a3c102724f2
Revises: 6fddadf786da
Create Date: 2025-10-31 22:37:03.725529

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3c102724f2'
down_revision: Union[str, Sequence[str], None] = '6fddadf786da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_SENSITIVE', 'RETURN', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )

    # Insert tag data
    tag_instructions = {
        'EXPRESS': 'Handle with priority shipping',
        'STANDARD': 'Process with regular shipping timeline',
        'FRAGILE': 'Handle with extra care',
        'HEAVY': 'Use appropriate lifting equipment',
        'INTERNATIONAL': 'Process through customs',
        'DOMESTIC': 'Route through local delivery network',
        'TEMPERATURE_SENSITIVE': 'Maintain specified temperature conditions',
        'RETURN': 'Process for return shipping'
    }

    for tag_name, instruction in tag_instructions.items():
        op.execute(
            f"""
            INSERT INTO tag (id, name, instruction)
            VALUES (gen_random_uuid(), '{tag_name}', '{instruction}')
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
